name: BackEnd CI workflow

on:
  push:
    branches:
      - 'master'
      
# Env variable
env:
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
    build: 
      runs-on: ubuntu-latest
      
      steps:
    
      - name: Checkout the master branch
        uses: actions/checkout@v1
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Build with Maven
        run: mvn -B package --file ./backend/pom.xml -DskipTests
        
      - name: list all the directory 
        run: ls -a 
        
      - name: list the terget folder
        run: |
          cd ./backend/target 
          ls -a
          

  
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Get current date # get the date of the build
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    
      - name: Build the Docker image # push The image to the docker hub
        run: docker build . --file ./backend/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/orderbird-backend:${{ steps.date.outputs.date }}
      
      - name: Docker push with date  
        run: docker push ${{ secrets.DOCKER_USERNAME }}/orderbird-backend:${{ steps.date.outputs.date }}
      
      - name: Tag the Docker image with latest 
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/orderbird-backend:latest
     
      - name: Docker Push with latest
        run: docker push ${{ secrets.DOCKER_USERNAME }}/orderbird-backend:latest  
       

          
 

          
   

